Repository wecode-bootcamp-korea/18-1st-KKAKKA-frontend, pull requests merged in 2021-03, with the labels that each got.

#3 [18기 이근화] Add: 회원가입 페이지 레이아웃 완료, 비밀번호 체크, input 입력 확인 및 정규식 로직 구현 완료, 백엔드와 통신 후 축하 페이지로 이동 구현 완료
  package-lock.json
  package.json
  public/images/coupon.png
  src/Pages/SignUp/Congratulation.js
  src/Pages/SignUp/Congratulation.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 진행중

#7 [18기 이근화] Add: 푸터 레이아웃 구현 완료
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Pages/Main/Main.js
Labels: Status: Conflict 해결요청

#10 [18기 이근화] Modified: 백엔드와 통신 후 key 값 및 레이아웃 수정
  src/Pages/Main/Components/Cards/Cards.scss
  src/Pages/Main/Main.js
  src/config.js
Labels: Status: 리뷰 요청

#8 [18기 남궁선아] Order 페이지 레이아웃 부분 구현, 이벤트 부분 구현완료
  src/Pages/FlowerList/LIstDatas.js
  src/Pages/Main/CardList.js
  src/Pages/Main/Main.scss
  src/Pages/Order/Components/FooterBtn/FooterBtn.js
  src/Pages/Order/Components/FooterBtn/FooterBtn.scss
  src/Pages/Order/Components/OrderAddress/AddressInput/AddressInput.js
  src/Pages/Order/Components/OrderAddress/AddressInput/AddressInput.scss
  src/Pages/Order/Components/OrderAddress/OrderAddress.js
  src/Pages/Order/Components/OrderAddress/OrderAddress.scss
  src/Pages/Order/Components/OrderLetter/OrderLetter.js
  src/Pages/Order/Components/OrderLetter/OrderLetter.scss
  src/Pages/Order/Components/OrderPay/OrderPay.js
  src/Pages/Order/Components/OrderPay/OrderPay.scss
  src/Pages/Order/Components/OrderPay/OrderProduct/OrderProduct.js
  src/Pages/Order/Components/OrderPay/OrderProduct/OrderProduct.scss
  src/Pages/Order/Order.js
  src/Pages/Order/Order.scss
  src/Routes.js
Labels: Status: 수정 요청

#13 [18기 남궁선아] 레이아웃 및 라우터 세부 수정, 백엔드 AWS 연결 완료 !!!
  public/data/FlowerList.json
  public/data/cookieData.json
  public/data/cookieSubscribe.json
  public/data/subscribeData.json
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/SubNav/SubNav.js
  src/Components/SubNav/SubNav.scss
  src/Pages/FlowerDetail/FlowerDetail.js
  src/Pages/FlowerDetail/FlowerDetail.scss
  src/Pages/FlowerList/FlowerList.js
  src/Pages/FlowerList/FlowerList.scss
  src/Pages/FlowerList/LIstDatas.js
  src/Pages/FlowerList/ListDatas.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Order/Order.js
  src/Pages/Order/Order.scss
  src/Pages/SignUp/SignUp.scss
  src/Pages/SubscribeList/SubCard/SubCard.js
  src/Pages/SubscribeList/SubStart/SubStart.js
  src/Pages/SubscribeList/SubscribeDetail/SubDetailCard.js
  src/Pages/SubscribeList/SubscribeDetail/SubscribeDetail.js
  src/Pages/SubscribeList/SubscribeList.js
  src/config.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#14 [18기 남궁선아] 회원가입 오류 수정, 쿠키공장 추가
  src/Components/Nav/Nav.js
  src/Pages/Event/Event.js
  src/Pages/Event/Event.scss
  src/Pages/FlowerList/FlowerList.scss
  src/Pages/FlowerList/LIstDatas.js
  src/Pages/Login/Login.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#15 [18기 남궁선아] Fix : 1차 프로젝트 최종발표
  src/Pages/Event/Event.js
Labels: Status: 리뷰 요청

#16 [18기 남궁선아] Fix : 메인페이지 데이터 경로 수정, SCSS 네스팅 오류 수정
  src/Pages/Event/Event.js
  src/Pages/Event/Event.scss
  src/Pages/Main/Components/DataList/DataList.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/SubscribeList/SubscribeDetail/Components/DetailOption/DetailOption.js
Labels: Status: 리뷰 요청
